"""Signal platform runtime components."""

from loot.signals.authorization import (
    AuthorizationConflictError,
    AuthorizationFacts,
    AuthorizationRepository,
    AuthorizationRepositoryError,
    InMemoryAuthorizationRepository,
    PolicyAuthorizationRepository,
    PolicyRecordResult,
    validate_authorization_references,
)
from loot.signals.state_machine import (
    DuplicateDecisionConflictError,
    ExpiredDecisionTicketError,
    ExpiredSignalTransitionError,
    InvalidAuthorizationChainError,
    InvalidSignalTransitionError,
    SignalAuthorizationContext,
    SignalExpiryResult,
    SignalContextConflictError,
    SignalInitializationConflictError,
    SignalInitializationRequest,
    SignalInitializationResult,
    SignalProjectionConflictError,
    SignalStateMachine,
    SignalStateMachineError,
    SignalTransitionMismatchError,
    SignalTransitionResult,
    SignalTransitionTimeError,
    SignalVersionConflictError,
    UntrustedDecisionTicketError,
)

__all__ = [
    "AuthorizationConflictError",
    "AuthorizationFacts",
    "AuthorizationRepository",
    "AuthorizationRepositoryError",
    "DuplicateDecisionConflictError",
    "ExpiredDecisionTicketError",
    "ExpiredSignalTransitionError",
    "InMemoryAuthorizationRepository",
    "InvalidAuthorizationChainError",
    "InvalidSignalTransitionError",
    "PolicyRecordResult",
    "PolicyAuthorizationRepository",
    "validate_authorization_references",
    "SignalAuthorizationContext",
    "SignalExpiryResult",
    "SignalContextConflictError",
    "SignalInitializationConflictError",
    "SignalInitializationRequest",
    "SignalInitializationResult",
    "SignalProjectionConflictError",
    "SignalStateMachine",
    "SignalStateMachineError",
    "SignalTransitionMismatchError",
    "SignalTransitionResult",
    "SignalTransitionTimeError",
    "SignalVersionConflictError",
    "UntrustedDecisionTicketError",
]
